/**
 * Aproximación fonética con ortografía familiar para hispanohablantes
 * (orientación, no sustituto del AFI).
 */
const MAP: Record<string, string> = {
  hello: 'jelóu',
  hi: 'jai',
  how: 'jau',
  meet: 'mit',
  please: 'plís',
  evening: 'íivning',
  bit: 'bit',
  sit: 'sit',
  fish: 'fish',
  live: 'liv',
  bed: 'bed',
  red: 'red',
  ten: 'ten',
  head: 'jed',
  cat: 'cat',
  hat: 'jat',
  bad: 'bad',
  man: 'man',
  cup: 'cap',
  but: 'bat',
  love: 'lav',
  sun: 'san',
  hot: 'jot',
  lot: 'lot',
  dog: 'dog',
  stop: 'stop',
  book: 'buk',
  put: 'put',
  good: 'gud',
  look: 'luk',
  about: 'abaut',
  banana: 'banána',
  the: 'da',
  a: 'a',
  see: 'sí',
  beach: 'bich',
  eat: 'it',
  key: 'ki',
  car: 'car',
  father: 'fadher',
  arm: 'arm',
  heart: 'jart',
  door: 'dor',
  more: 'mor',
  law: 'lo',
  call: 'col',
  food: 'fud',
  blue: 'blu',
  shoe: 'shu',
  moon: 'mun',
  bird: 'berd',
  word: 'uerd',
  nurse: 'ners',
  learn: 'lern',
  day: 'dei',
  make: 'meik',
  rain: 'rein',
  say: 'sei',
  my: 'mai',
  time: 'taim',
  like: 'laik',
  buy: 'bai',
  boy: 'boi',
  toy: 'toi',
  coin: 'coin',
  voice: 'vois',
  now: 'nau',
  out: 'aut',
  house: 'jaus',
  go: 'gou',
  home: 'houm',
  show: 'shou',
  know: 'nou',
  think: 'zinc',
  three: 'zrí',
  thank: 'zank',
  bath: 'baz',
  this: 'dis',
  that: 'dat',
  mother: 'madher',
  weather: 'wedher',
  she: 'shi',
  ship: 'ship',
  wash: 'wosh',
  tank: 'tank',
  sink: 'sink',
  thing: 'zing',
  table: 'teibl',
  water: 'wóter',
  begin: 'bigín',
  decide: 'disáid',
  window: 'uíndou',
  nation: 'néishon',
  measure: 'mézher',
  vision: 'vízhon',
  garage: 'garásh',
  decision: 'disízhon',
  very: 'verri',
  have: 'jav',
  never: 'néver',
  sing: 'sing',
  ring: 'ring',
  running: 'ráning',
  right: 'rait',
  happy: 'japi',
  student: 'stiudent',
  relax: 'riláks',
  prefer: 'prifér',
  present: 'présent',
  record: 'rékord',
  object: 'óbdzhekt',
  information: 'informéishon',
  education: 'ediukéishon',
  television: 'télevizhon',
  economic: 'ikonómic',
  fantastic: 'fantástic',
  democratic: 'demokrátic',
  scientific: 'sayentífic',
  football: 'fútbol',
  bedroom: 'béd-rum',
  sunglasses: 'san-glásess',
  toothpaste: 'tuth-peist',
  knife: 'naif',
  knee: 'ní',
  knock: 'nok',
  knight: 'náit',
  write: 'rait',
  wrong: 'rong',
  wrap: 'rap',
  wrist: 'rist',
  climb: 'klaim',
  thumb: 'zam',
  bomb: 'bom',
  doubt: 'daut',
  debt: 'det',
  hour: 'áuer',
  honest: 'ónest',
  honor: 'ónor',
  honour: 'ónor',
  heir: 'éar',
  sign: 'sain',
  design: 'disáin',
  foreign: 'fóren',
  gnat: 'nat',
  talk: 'tok',
  walk: 'wok',
  could: 'cud',
  would: 'wud',
  half: 'jaf',
  calm: 'kam',
  listen: 'lisen',
  castle: 'cásel',
  whistle: 'guisel',
  often: 'ófen',
  christmas: 'krísmas',
  cute: 'kiut',
  washington: 'wóshington',
  breakfast: 'brekfest',
  comfortable: 'kómfortabol',
  wednesday: 'uénzdei',
  bought: 'bot',
  through: 'zru',
  recipe: 'rézipi',
  vegetable: 'védshtabol',
  archaeology: 'arkiólody',
  inevitably: 'inevítabli',
  thorough: 'záro',
  conscientious: 'konshiénshos',
  entrepreneurial: 'ontraprenórial',
  receipt: 'risít',
  briefcase: 'brífkeis',
  broadcast: 'bródkast',
  buckfast: 'bakfast',
  shape: 'sheip',
  shop: 'shop',
  thin: 'zin',
  toffee: 'tofi',
  copies: 'ópis',
  fool: 'ful',
  fall: 'fol',
  few: 'fiu',
  full: 'ful',
  vulnerable: 'vólnerabol',
  variable: 'vériabol',
  considerable: 'konsíderabol',
  compatible: 'kompatíbol',
  comparable: 'komparabol',
  preacher: 'prícher',
  teenager: 'tínedcher',
  ice: 'ais',
  be: 'bí',
  come: 'kam',
  get: 'guet',
  give: 'giv',
  tell: 'tel',
  find: 'faind',
  break: 'breik',
  choose: 'chus',
  draw: 'dro',
  feel: 'fil',
  fly: 'flai',
  grow: 'grou',
  hang: 'jang',
  hide: 'jaid',
  hit: 'jit',
  hold: 'jould',
  hurt: 'jert',
  lend: 'lend',
  lie: 'lai',
  lose: 'lus',
  pay: 'pei',
  quit: 'kuit',
  ride: 'raid',
  rise: 'rais',
  shut: 'shat',
  sleep: 'slip',
  speak: 'spik',
  steal: 'stil',
  swim: 'suim',
  tear: 'téar',
  throw: 'zrou',
  wake: 'weik',
  wear: 'uéar',
  win: 'uin',
  burst: 'berst',
  deal: 'dil',
  feed: 'fid',
};

export function spanishApproxForWord(word: string): string | undefined {
  const norm = word
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
  const firstToken = norm.split(/[\s(/]/)[0] ?? '';
  const kFull = norm.replace(/[^a-z]/g, '');
  const kTok = firstToken.replace(/[^a-z]/g, '');
  return MAP[kFull] ?? MAP[kTok];
}

/**
 * Devuelve la aproximación fonética de una frase completa (una o varias palabras).
 * Las palabras sin entrada en el mapa se mantienen en minúsculas tal cual.
 * Retorna undefined si ninguna palabra tiene una aproximación diferente al original.
 */
export function spanishApproxForPhrase(phrase: string): string | undefined {
  const words = phrase.trim().split(/\s+/);
  if (words.length === 1) return spanishApproxForWord(words[0]);

  let hasChange = false;
  const parts = words.map(w => {
    const approx = spanishApproxForWord(w);
    if (!approx) return w.toLowerCase();
    const original = w.toLowerCase().replace(/[^a-z]/g, '');
    if (approx !== original) hasChange = true;
    return approx;
  });

  // Siempre devuelve algo para frases (aunque ninguna palabra esté en el mapa)
  return hasChange ? parts.join(' ') : parts.join(' ') || undefined;
}
